### ISSUE TITLE
Developing Data Products first Docker link gives 404 error

### ISSUE THREAD

**Issue by WatHughes** [DataScienceSpecialization/DataScienceSpecialization.github.io#103]
This link: 

http://www.flaviobarros.net/2015/04/30/dockerizing-a-shiny-app/

I suspect this link will fix the problem. Note the missing g:

http://www.flaviobarros.net/2015/04/30/dockerizin-a-shiny-app/

or this one:

http://www.rmining.net/2015/04/30/dockerizing-a-shiny-app/

**Comment by seankross** [comment]
Fixed! Thank you!
