### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MMohey** [DataScienceSpecialization/DataScienceSpecialization.github.io#126]
A broken link under:

[http://datasciencespecialization.github.io](http://datasciencespecialization.github.io/) > [Exploratory Data Analysis](http://datasciencespecialization.github.io/eda/) > [Data Analysis using Twitter API and Python](http://blog.impiyush.me/2015/03/data-analysis-using-twitter-api-and.html)

**Comment by seankross** [comment]
Fixed in #126
