### ISSUE TITLE
Swirl package 

### ISSUE THREAD

**Issue by naveenkirane** [DataScienceSpecialization/DataScienceSpecialization.github.io#66]
Hi, 
Often I observed that during swirl classes, the module expects you to write the code in exactly the same way the module was built to accept. Example
1. filter(cran,size>100500 & r_os=="linux-gnu")
2. filter(cran,size>100500 , r_os=="linux-gnu")
both the above codes yield same result, but only 2 is accepted as corrected and allows to proceed further. It would be great if module accepts any code that yield correct results rather than expecting exact code it needed.

Secondly, when we try ntimes and cant get the answer, there should be an option to proceed further by showing the solution to problem where we struck. This way we can give n attempts and continue further when we no more solve the problem.

**Comment by imeikle** [comment]
Doesn't skip() do what you want for point 2?

**Comment by seankross** [comment]
Hi @naveenkirane,

- The authors of Swirl courses can accept as many different answers as they wish to, but that decision is made by the individual Swirl course authors. 
- In order to move past a question you should use the `skip()` function.
