### ISSUE TITLE
Request to change the link to my resource

### ISSUE THREAD

**Issue by homerhanumat** [DataScienceSpecialization/DataScienceSpecialization.github.io#99]
Hello,

On the following page:

[https://github.com/DataScienceSpecialization/DataScienceSpecialization.github.io/blob/master/ddp.md](https://github.com/DataScienceSpecialization/DataScienceSpecialization.github.io/blob/master/ddp.md)

the Shiny Simulation tutorial link takes you to a an app that is hosted on my `shinyapps` account.  A lot of people have been checking it out -- to the tune of about 600 user-hours per month.  I feel the need to reduce this figure, so  I wonder if you could instead link to my GitHub repo URL:

[https://github.com/homerhanumat/shinyTutorials](https://github.com/homerhanumat/shinyTutorials)

The repo's README file contains instructions on cloning the repo and running the app locally.  Coursera folks who are not GitHub users (presumably there are very few of these) would still have the option to view the remotely-hosted app.

Thanks,
Homer

**Comment by seankross** [comment]
No problem, just did this. Thanks again for making this tutorial and sharing it with the community.

**Comment by homerhanumat** [comment]
Thanks!
